spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=order_mgmt_db
    username: fashionUser
    password: fashion2k25
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#server:
  #port: 8080

app:
  base-url: http://localhost:8080/api

  #fashionUser
  #fashion2k25

  # databaseName=loginedUser
  # username: mohdtest
  # password: Btech@2k21