spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=customer_mgmt_db
    username: fashionUser
    password: fashion2k25
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#server:

  base-url: http://localhost:8080/api
