spring:
  datasource:
    url: jdbc:sqlserver://10.0.2.20:1433;databaseName=alvora_preprod
    username: preprod_user
    password: PreProd@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB

  cloudinary:
    cloud-name: dz8fvgbrs
    api-key: 189877976637468
    api-secret: qxWVu4CRG_074jCvJcY_NlIWPoY

server:
  port: 8084

app:
  base-url: https://preprod.alvora.com/api
